- name: Checkout znc-push
  sudo: yes
  git: repo=https://github.com/jreese/znc-push dest={{ znc_datadir }}/lib/znc-push

- name: Build znc-push
  sudo: yes
  command: make chdir={{ znc_datadir }}/lib/znc-push

- name: Install znc-push
  sudo: yes
  command: mv {{ znc_datadir }}/lib/znc-push/push.so {{ znc_datadir }}
