- name: Install ZNC
  become: yes
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - znc
    - znc-dev
    - znc-perl
    - znc-python

- name: Create a ZNC group
  become: yes
  become_user: root
  group: name=znc state=present

- name: Create a ZNC user
  become: yes
  become_user: root
  user: name=znc state=present system=yes group=znc home={{ znc_datadir }}

- name: Add the ZNC systemd script
  become: yes
  become_user: root
  copy: src=etc/systemd/system/znc.service
        dest=/etc/systemd/system/znc.service
        owner=root
        group=root
        mode=0644

- name: Enable the ZNC service
  become: yes
  become_user: root
  service: name=znc state=started enabled=yes
  ignore_errors: yes

- name: Create a directory for plugin repos
  become: yes
  become_user: root
  file: path={{ znc_datadir }}/lib/ state=directory owner=znc group=znc

- include: znc-push.yml user=znc
