sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t pi .
  - docker run --rm --interactive --tty --volume sys/fs/cgroup:/sys/fs/cgroup:ro --cap-add=SYS_ADMIN pi true
