---

- name: Install some useful packages
  become: yes
  become_user: root
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - gcc
    - git
    - linux-tools
    - sudo
    - tmux
    - zsh

- name: Install some useful Debian/Ubuntu specific packages
  become: yes
  become_user: root
  apt: pkg={{ item }} state=installed
  with_items:
    - apt-transport-https
    - debian-goodies
    - python-software-properties
    - unattended-upgrades
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: python.yml
- include: web.yml
