---

- name: Update apt cache
  sudo: yes
  apt: update_cache=yes

- name: Install some useful packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - build-essential
    - gcc
    - git
    - sudo
    - tmux
    - vim-nox
    - zsh

- name: Install some useful Debian/Ubuntu specific packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - apt-transport-https
    - debian-goodies
    - python-software-properties
    - systemd
    - systemd-sysv
    - unattended-upgrades
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: python.yml tags=python
- include: ssl.yml tags=ssl
- include: web.yml tags=web
