---

- name: Install Twisted
  become: yes
  become_user: root
  command: pypy -m pip install --quiet pyopenssl pycrypto twisted

- name: Install PiPy
  become: yes
  become_user: root
  command: pypy -m pip install {{ pipy }}

- name: Create a PiPy group
  become: yes
  become_user: root
  group: name={{ pipy_user }} state=present

- name: Create a PiPy user
  become: yes
  become_user: root
  user: name={{ pipy_user }}
        state=present
        system=yes
        group={{ pipy_user }}
        groups=ssl-cert
        home=/srv/pipy

- name: Add a PiPy Service
  become: yes
  become_user: root
  template: src=etc/systemd/system/pipy.service
            dest=/etc/systemd/system/pipy.service
            owner=root
            group=root
            mode=0644
  notify:
    reload systemd

- name: Start PiPy
  become: yes
  become_user: root
  service: name=pipy state=started enabled=yes
